# Generated by Django 6.0.6 on 2026-07-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporation_name', models.CharField(max_length=255)),
                ('corporation_type', models.CharField(blank=True, max_length=100)),
                ('homepage_url', models.URLField(blank=True)),
                ('has_care_management', models.BooleanField(default=False)),
                ('has_home_nursing', models.BooleanField(default=False)),
                ('has_home_care', models.BooleanField(default=False)),
                ('has_day_service', models.BooleanField(default=False)),
                ('has_day_care', models.BooleanField(default=False)),
                ('has_geriatric_health_facility', models.BooleanField(default=False)),
                ('has_senior_housing', models.BooleanField(default=False)),
                ('has_paid_nursing_home', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
