# Generated by Django 6.0.6 on 2026-07-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_date', models.DateField()),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('case_count', models.IntegerField(default=0)),
                ('contract_count', models.IntegerField(default=0)),
                ('care_manager_name', models.CharField(blank=True, max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to='hospitals.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
