# Generated by Django 6.0.6 on 2026-07-05 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('api', 'API'), ('manual', '手動')], default='csv', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_file_path', models.CharField(blank=True, max_length=500)),
                ('converted_csv_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('reviewing', 'レビュー中'), ('applied', '反映済み'), ('failed', '失敗')], default='draft', max_length=30)),
                ('total_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('update_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('applied_count', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(default=0)),
                ('action_type', models.CharField(choices=[('create', '新規'), ('update', '更新'), ('error', 'エラー'), ('skip', 'スキップ')], default='create', max_length=20)),
                ('hospital_name', models.CharField(max_length=255)),
                ('corporation_name', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('diff_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records', to='hospitals.hospital')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='importer.importsession')),
            ],
        ),
    ]
