# Generated by Django 6.0.6 on 2026-07-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField()),
                ('visit_method', models.CharField(blank=True, choices=[('visit', '訪問'), ('phone', '電話'), ('email', 'メール'), ('online', 'オンライン'), ('event', '研修・勉強会'), ('other', 'その他')], max_length=50)),
                ('visitor_name', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('positive_response', models.TextField(blank=True)),
                ('concern', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('information_level', models.CharField(choices=[('official', '公式情報'), ('confirmed', '確認済み'), ('heard', '聞き取り'), ('rumor', '未確認')], default='heard', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('follow_status', models.CharField(choices=[('todo', '未対応'), ('doing', '対応中'), ('done', '完了')], default='todo', max_length=20)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_records', to='contacts.contactperson')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='hospitals.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
