# Generated by Django 6.0.6 on 2026-07-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('homepage_url', models.URLField(blank=True)),
                ('total_beds', models.IntegerField(default=0)),
                ('general_beds', models.IntegerField(default=0)),
                ('chronic_beds', models.IntegerField(default=0)),
                ('psychiatric_beds', models.IntegerField(default=0)),
                ('community_beds', models.IntegerField(default=0)),
                ('recovery_beds', models.IntegerField(default=0)),
                ('disability_beds', models.IntegerField(default=0)),
                ('other_beds', models.IntegerField(default=0)),
                ('has_regional_cooperation', models.BooleanField(default=False)),
                ('regional_department_name', models.CharField(blank=True, max_length=255)),
                ('msw_count', models.IntegerField(default=0)),
                ('discharge_nurse_count', models.IntegerField(default=0)),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='corporations.corporation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
